services:
  db:
    image: postgres:18.3
    env_file: .env.local
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 8080:5432

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  web:
    build: 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file: .env.local
    depends_on:
      - db
      - redis

volumes:
  pgdata:

