# Generated by Django 6.0.5 on 2026-05-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0002_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='last_notified_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='notification_cooldown_minutes',
            field=models.PositiveIntegerField(default=360),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='pulse.airport'),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='pulse.airport'),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('triggered', 'Triggered'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
